# Generated by Django 5.1 on 2024-12-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField()),
                ('num_items', models.IntegerField()),
                ('items', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
