# Generated by Django 5.1 on 2024-12-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='creator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracket',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='items',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
