# Generated by Django 5.1 on 2024-12-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bracket_creator_bracket_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='winner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
